# Generated by Django 3.2.7 on 2021-12-02 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PuppyKind',
            fields=[
                ('kind', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('section', models.TextField(blank=True, null=True)),
                ('label_3', models.TextField(blank=True, db_column='LABEL-3', null=True)),
                ('label_4', models.TextField(blank=True, db_column='LABEL-4', null=True)),
                ('smallavg_kg_field', models.IntegerField(blank=True, db_column='smallavg(kg)', null=True)),
                ('bigavg_kg_field', models.IntegerField(blank=True, db_column='bigavg(kg)', null=True)),
            ],
            options={
                'db_table': 'puppy_kind',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Puppy',
            fields=[
                ('name', models.CharField(max_length=200, null=True)),
                ('kind', models.CharField(max_length=200, null=True)),
                ('Primary_weight', models.FloatField(null=True)),
                ('gender', models.CharField(max_length=200, null=True)),
                ('neutralization', models.BooleanField(default=True)),
                ('birth_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('animal_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
