# Generated by Django 3.2.7 on 2021-11-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='puppy_kind',
            fields=[
                ('kind', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('section', models.TextField(blank=True, null=True)),
                ('label_3', models.TextField(blank=True, db_column='LABEL-3', null=True)),
                ('label_4', models.TextField(blank=True, db_column='LABEL-4', null=True)),
                ('smallavg_kg_field', models.IntegerField(blank=True, db_column='smallavg(kg)', null=True)),
                ('bigavg_kg_field', models.IntegerField(blank=True, db_column='bigavg(kg)', null=True)),
            ],
            options={
                'db_table': 'puppy_kind',
                'managed': False,
            },
        ),
    ]
