# Generated by Django 3.2.7 on 2021-12-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puppy',
            name='animal_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
