# Generated by Django 3.2.7 on 2021-12-01 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0002_puppy_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuppyKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.TextField(blank=True, null=True)),
                ('section', models.TextField(blank=True, null=True)),
                ('label_3', models.TextField(blank=True, db_column='LABEL-3', null=True)),
                ('label_4', models.TextField(blank=True, db_column='LABEL-4', null=True)),
                ('smallavg_kg_field', models.IntegerField(blank=True, db_column='smallavg(kg)', null=True)),
                ('bigavg_kg_field', models.IntegerField(blank=True, db_column='bigavg(kg)', null=True)),
            ],
            options={
                'db_table': 'puppy_kind',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='puppy_kind',
        ),
    ]
