# Generated by Django 3.2.7 on 2021-12-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kindage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(blank=True, db_column='Num', null=True)),
                ('kind', models.TextField(blank=True, db_column='Kind', null=True)),
                ('age', models.TextField(blank=True, db_column='Age', null=True)),
                ('min', models.FloatField(blank=True, db_column='Min', null=True)),
                ('max', models.FloatField(blank=True, db_column='Max', null=True)),
            ],
            options={
                'db_table': 'kindage',
                'managed': False,
            },
        ),
    ]
