# Generated by Django 3.2.7 on 2021-12-02 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kindage',
            fields=[
                ('num', models.IntegerField(blank=True, db_column='Num', primary_key=True, serialize=False)),
                ('kind', models.TextField(blank=True, db_column='Kind', null=True)),
                ('age', models.TextField(blank=True, db_column='Age', null=True)),
                ('min', models.FloatField(blank=True, db_column='Min', null=True)),
                ('max', models.FloatField(blank=True, db_column='Max', null=True)),
            ],
            options={
                'db_table': 'kindage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IndiWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('weight', models.FloatField(null=True)),
                ('puppy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dog.puppy')),
            ],
        ),
    ]
